resource_pack:
  apply_on_join: true
  kick_player_on_decline: true
  link: 'http://www.matteodev.it/spigot/realmoney/res/RealMoney3.3.zip'
  delay_ticks: 15
  show_loading_message: true
  show_success_message: true
# You can customize your money icons:
# It supports Minecraft materials, ItemsAdder items and head textures strings.
# Example vanilla: GOLD_NUGGET
# Example ItemsAdder: ruby
# Example head texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjBhN2I5NGM0ZTU4MWI2OTkxNTlkNDg4NDZlYzA5MTM5MjUwNjIzN2M4OWE5N2M5MzI0OGEwZDhhYmM5MTZkNSJ9fX0=
item_icon:
  coin: default
  banknote: default
  sack_of_money: default
item_icon_thresholds:
  coin: 0
  banknote: 5
  sack_of_money: 100
pickup_sound:
  enabled: true
  type: ENTITY_EXPERIENCE_ORB_PICKUP
  volume: 2.0
  pitch: 6.0
# Increase this id to make old banknotes, coins and sack_of_money not working anymore
cash_id:
  id: 1
show_actionbar_messages: true
show_player_name_sack_of_money: false
loots:
  from_entities: true
  from_blocks: true
  from_fishes: true
placed_blocks_drop_money:
  creative: true
  survival: false
get_money_method:
  press_f: true
  right_click: false
spawners:
  enable: true
  percentage_of_money: 35
remove_decimals:
  enabled: false
  approximate_bigger: true
pickups_merge:
  enabled: true
  radius: 4
  min_pickups: 6
allow_money_in_hoppers: false
allow_entities_pickup_money: false
disabled_worlds:
  - example_world
multipliers_groups:
  drop:
    "1": 1
    "2": 2
    "3": 3
    "4": 4
    "5": 5
    "10": 10
  pickup:
    "1": 1
    "2": 2
    "3": 3
    "4": 4
    "5": 5
    "10": 10
